export const workerNames = [
    "Aarav Patil",
    "Anaya Deshmukh",
    "Advait Joshi",
    "Ishan Pawar",
    "Tanvi Chavan",
    "Kavya More",
    "Yash Kulkarni",
    "Riya Sawant",
    "Vedant Gaikwad",
    "Sai Mehta",
    "Aarohi Shah",
    "Atharva Mane",
    "Pari Khare",
    "Avani Gokhale",
    "Aryan Malhotra",
    "Ishaan Raut",
    "Arnav Phatak",
    "Kiara Nair",
    "Arush Thakur",
    "Anika Patwardhan",
    "Aahana Sharma",
    "Reyansh Dalvi",
    "Sara Paranjape",
    "Dhruv Shahane",
    "Anvi Godbole"
  ];
  